### ISSUE TITLE
Move Word2Vec.jl to JuliaText?

### ISSUE THREAD

**Issue by weijianzhg** [JuliaText/Roadmap.jl#2]
Hi @malmaud, 

Is this the organization for text mining in Julia? 

I wrote a Julia interface to word2vec (https://github.com/weijianzhang/Word2Vec.jl) and 
I am happy to move it here if needed. 

Best wishes,

Weijian

**Comment by malmaud** [comment]
Yep, that's the ambition. We'd love to have word2vec here.

**Comment by weijianzhg** [comment]
Thanks @malmaud,

I am not sure how it works. Should we do something similar to JuliaML?

> you'll have commit access to any packages that you author and transfer to JuliaML. Whether or not you have commit access to other packages will be up to the maintainers of those packages.

See https://groups.google.com/forum/#!searchin/julia-users/juliaML/juliausers/vMJHZmTRiuk/2esE_6NpBQAJ

**Comment by malmaud** [comment]
Sure

**Comment by weijianzhg** [comment]
Could you send me an invite to JuliaText?

**Comment by malmaud** [comment]
Done

**Comment by weijianzhg** [comment]
Thanks.
