### ISSUE TITLE
Logo for JuliaText

### ISSUE THREAD

**Issue by weijianzhg** [JuliaText/Roadmap.jl#3]
Merry Christmas everyone!
Should we have a logo for JuliaText? @malmaud @johnmyleswhite @ninjin @StefanKarpinski
What about this one?
![12399456_985447058164229_1179815316_n](https://cloud.githubusercontent.com/assets/7595454/11990428/52845c86-aa05-11e5-8621-068b688b1011.jpg)

**Comment by aviks** [comment]
Paging @cormullion , our logo builder extraordinaire.

**Comment by cormullion** [comment]
If it rains this weekend, that's what I'll be doing...:) 

# Edit

It rained this afternoon... :) Here are a few ideas to get the ball rolling.

![screen shot 2017-09-09 at 16 15 50](https://user-images.githubusercontent.com/52289/30241476-10a78a36-957c-11e7-9be2-439c305ec14e.png)

It's all Julia code, so it's easy enough to make permutations and combinations...

**Comment by oxinabox** [comment]
Lets solve this in the next few days/week, maybe yes?

My preference of the ones so far are either of the bottom two of @cormullion 's 
Prob bottom right

None of them really say language strongly to me.
But that one comes closest I think.
(Vaguely makes me think of information retrieval more than anything else, i guess apparently I associate lined paper with that)


But I'ld prefer anything over the current gravitar

**Comment by aviks** [comment]
I could get behind number 4. 

My creative skills are nonexistent, but some potential ideas : 

* Something with a speech buble? 
* The `a` sound in many scripts? 
* The list of languages I'll support in Languages.jl, in their native script: 

|Code|English Name|Native Name
|---|---|---
epo|Esperanto|Esperanto
eng|English|English
rus|Russian|Русский
cmn|Mandarin|官话
spa|Spanish|Español
por|Portuguese|Português
ita|Italian|Italiano
ben|Bengali|বাংলা|210
fra|French|Français
deu|German|Deutsch
ukr|Ukrainian|Українська
kat|Georgian|ქართული
arb|Arabic|العربية
hin|Hindi|हिन्दी
jpn|Japanese|日本語
heb|Hebrew|עברית
ydd|Yiddish|ייִדיש
pol|Polish|Polski
amh|Amharic|አማርኛ
tir|Tigrinya|ትግርኛ
jav|Javanese|Basa Jawa
kor|Korean|한국어
nob|Bokmal|Bokmål
nno|Nynorsk|Nynorsk
dan|Danish|Dansk
swe|Swedish|Svenska
fin|Finnish|Suomi
tur|Turkish|Türkçe
nld|Dutch|Nederlands
hun|Hungarian|Magyar
ces|Czech|Čeština
ell|Greek|Ελληνικά
bul|Bulgarian|Български
bel|Belarusian|Беларуская
mar|Marathi|मराठी
kan|Kannada|ಕನ್ನಡ
ron|Romanian|Română|24
slv|Slovene|Slovenščina|2.5
hrv|Croatian|Hrvatski|7
srp|Serbian|Српски|8.7
mkd|Macedonian|Македонски|2
lit|Lithuanian|Lietuvių|4
lav|Latvian|Latviešu|2
est|Estonian|Eesti|1.1
tam|Tamil|தமிழ்|70
vie|Vietnamese|Tiếng Việt|75
urd|Urdu|اُردُو|66
tha|Thai|ภาษาไทย|56
guj|Gujarati|ગુજરાતી|50
uzb|Uzbek|Oʻzbekcha|27
pan|Punjabi|ਪੰਜਾਬੀ|100
azj|Azerbaijani|Azərbaycanca|26
ind|Indonesian|Bahasa Indonesia|150
tel|Telugu|తెలుగు|85
pes|Persian|فارسی|50
mal|Malayalam|മലയാളം|38
hau|Hausa|Hausa|44
ori|Oriya|ଓଡ଼ିଆ|36
mya|Burmese|မြန်မာစာ|33
bho|Bhojpuri|भोजपुरी|40
tgl|Tagalog|Tagalog|30
yor|Yoruba|Yorùbá|28
mai|Maithili|मैथिली|15
orm|Oromo|Oromoo|25
ibo|Igbo|Igbo|25
ceb|Cebuano|Cebuano|21
kur|Kurdish|Kurdî|20
mlg|Malagasy|Malagasy|18
skr|Saraiki|سرائیکی|20
nep|Nepali|नेपाली|16
sin|Sinhalese|සිංහල|16
khm|Khmer|ភាសាខ្មែរ|16
tuk|Turkmen|Türkmençe|9
som|Somali|Soomaaliga|17
nya|Chewa|Chichewa|12
aka|Akan|Akan|11
zul|Zulu|IsiZulu|12
kin|Kinyarwanda|Kinyarwanda|10
hat|Haitian Creole|Kreyòl ayisyen|10
ilo|Ilocano|Ilokano|9
run|Rundi|Ikirundi|9
sna|Shona|ChiShona|8
uig|Uyghur|ئۇيغۇرچە|25

**Comment by cormullion** [comment]
Ha, I’d forgotten about these. I see I interpreted “text” wrongly, since it’s more about language and less about writing...

**Comment by weijianzhg** [comment]
I like number 4

**Comment by cormullion** [comment]
I did a few more.

5 I think speech bubbles kind of work - obviously not all language is spoken, but if you have three it suggests language/communication a bit better

![julia-text-5](https://user-images.githubusercontent.com/52289/39360520-812488c8-4a16-11e8-9348-38d9f26c23ea.png)

6 Speech bubbles look a bit like quotation marks, too...

![julia-text-2a](https://user-images.githubusercontent.com/52289/39512388-bd233984-4de8-11e8-83db-2a86c053b0e6.png)

7 Trying to channel a world/diverse languages/Julia-colored rainbow here:

![julia-text-4](https://user-images.githubusercontent.com/52289/39511823-b476fb7e-4de6-11e8-93d1-dc047924a766.png)

8 The justification for the purely English text is of course the name of the organization itself... ;)

![julia-text-8](https://user-images.githubusercontent.com/52289/39360519-810bbf0a-4a16-11e8-8f0e-2d5b0f5028b2.png)

**Comment by cormullion** [comment]
@scottpjones There’s a few spare ones here... 😀

**Comment by oxinabox** [comment]
Number 4 and Number 6 are currently my favs

**Comment by weijianzhg** [comment]
Happy with number 6 as well. Looks nice! Thanks @cormullion 

@aviks  @malmaud @ninjin any comments?

**Comment by ScottPJones** [comment]
I'm very happy with the one I got (and the great blog post!)
I also like 4 and 6
The old one, 2, with the spiraling text, is a lot like what I'd talked about for JuliaString.
How about a spiral with the color gradient like you did for JuliaString?
(instead of just "JuliaText" though, it could say "JuliaText" at the start (where it's largest, and start up at the top), and then have the word "text" translated into many of the languages on that list (separated by a space), spiraling inwards.

BTW, if you all do get a Genuine @cormullion Logo ™️, who would I have to bribe to get to be a member of `JuliaText`? 😁🤓

**Comment by weijianzhg** [comment]
Use number 6. Close this for now

**Comment by oxinabox** [comment]
Sold!

**Comment by cormullion** [comment]
Thanks! Very nice of you. Now I'm worrying about the jaggies around the edges. :) Later perhaps...

**Comment by cormullion** [comment]
Before I throw the code away:

```
using Luxor

"""
    speechbubble(radius, location, offset)
"""
function speechbubble(s, k, o)
    @layer begin
        n = squircle(O, s/2, s/2, vertices=true, rt=0.4)
        a = length(n)
        v = mod1(convert(Int, floor(k * a)), a)
        n[v] = between(O, n[v], o)
        poly(n, :fill, close=true)
    end
end

function textstroke(s, pos, action)
    @layer begin
        translate(pos)
        te = textextents(s)
        move(-te[3]/2, te[4] + te[2]/2)
        textpath(s)
        tp = pathtopoly()
        poly.(tp, action, close=true)
    end
end

@svg begin
    cols = [Luxor.darker_red, Luxor.darker_green, Luxor.darker_purple]
    sethue(cols[3])
    speechbubble(230, 0.14, 1.25)
    sethue("white")
    fontface("TiffanyStd-Heavy")

    fontsize(280)
    translate(0, 140)
    setline(6)

    sethue("white")
    textstroke("”", Point(-30, -10), :stroke)

    sethue(cols[1])
    textstroke("”", Point(-30, -10), :fill)

    sethue("white")
    textstroke("“", Point(10, 70), :stroke)

    sethue(cols[2])
    textstroke("“", Point(10, 70), :fill)
end 256 256
```

Font is ITC Tiffany Heavy, the fattest quotation marks I could find.
