### ISSUE TITLE
Is this dead?  (No, no, 'e's uh,...he's resting)

### ISSUE THREAD

**Issue by oxinabox** [JuliaText/Roadmap.jl#4]
I've been working on making loaded for each and every corpus I encounter in my research,
and putting them in a package. [CorpusLoaders.jl](https://github.com/oxinabox/CorpusLoaders.jl/)
Its not yet stable enough to be registered. But it is getting there.

I'ld love to see more NLP in julia, it seems rather quiet here, though

(In case you missed the joke: [Monty Python's Dead Parrot Sketch](https://www.youtube.com/watch?v=4vuW6tQ0218))

**Comment by tbreloff** [comment]
Want to merge into JuliaML?

**Comment by oxinabox** [comment]
@tbreloff I don't think there is anything in JuliaText to be merged.
Word2Vec.jl is a fork that is lagging behind the registered master.

CoreNLP.jl is a never registered package, that apparently supports Julia 0.2-

---

Re: CorpusLoaders.jl. I think it would be better to have a JuliaLinguistics organization for NLP/Computational Linguistics.
(or perhaps bring JuliaText back from the dead? But JuliaLinguistics seems a better name).
The overlap with machine learning is a bit too partial, don't you think?

If such a JuliaLinguistics Org did exist, it could hold a `LingusticsBase`
package.
And @jbn 's [WordNet.jl](https://github.com/jbn/WordNet.jl), and my CorpusLoaders.jl,
could both depend on it to define common function names.
And then [they would stop having namespace clashes.](http://stackoverflow.com/a/39558645/179081)

**Comment by tbreloff** [comment]
That's fine.... I guess the question was more "should NLP live in JuliaML"?  Happy to take your lead.

**Comment by oxinabox** [comment]
> That's fine.... I guess the question was more "should NLP live in JuliaML"? Happy to take your lead.

I'm not hard against it, but if you look at something like WordNet.jl,
it isn't at all ML focuses.
But it is a pretty important resource for both NLP people, and for (Computational) Linguistics people.
and then there are all the graph theory models -- idk what the intersection of graph theory and ML is like; I've not seen much, except BackPropThroughStructure.
(which are not at all my game, _my_ stuff actually does kinda fit into ML much better. But none of it is in public repos right now)

This can be revisitted later, I'm still weeks away from releasing CorpusLoaders,
and thus still weeks away from really needing a home for it.

**Comment by aviks** [comment]
'e's up.
