### ISSUE TITLE
Deprecate unmaintained packages and delete old forks

### ISSUE THREAD

**Issue by oxinabox** [JuliaText/Roadmap.jl#6]
I suggest that as a Org, we do not accept any non-canonical forks -- they will be perpretually out of date.
I suggest we delete the ones we have,
and ask for transfer instead.
This applies to Word2Vec.jl
Though we don't necessarily want a transfer, if the package it not being maintained.

I suggest unless CoreNLP.jl gets an update, it should have "Deprecated" added to its description.
Like is done in JuliaStats

**Comment by mkborregaard** [comment]
I just checked out this org, looked at the repo update dates, clicked on Word2Vec and saw it was failing, and decided the org had been abandoned. Then I saw this issue from 6 days ago! A good argument for not keeping old packages around.

**Comment by oxinabox** [comment]
@mkborregaard  we are trying  to  reboot it,  join the @natural-language channel on julia slack.

**Comment by aviks** [comment]
@weijianzhang The word2vec repo in this org is a fork. Do you intend to to transfer the repo to this org, or should we delete the fork?

**Comment by weijianzhg** [comment]
@aviks I am happy to transfer the repo to this org.

**Comment by weijianzhg** [comment]
@aviks Just transferred word2vec to JuliaText

**Comment by oxinabox** [comment]
Ok, and I have marked CoreNLP as deprecated,
so I think we are done
